openapi: 3.1.0
info:
  title: LionSpace Intelligence API
  description: Real-time intelligence and threat analysis platform API
  version: 1.0.0
  contact:
    name: LionSpace Team
    email: api@lionspace.io

servers:
  - url: https://api.lionspace.io/v1
    description: Production server
  - url: http://localhost:3000/api/v1
    description: Development server

security:
  - bearerAuth: []
  - apiKey: []

paths:
  /intelligence/feed:
    get:
      tags:
        - Intelligence
      summary: Get real-time intelligence feed
      description: Stream real-time intelligence data using Server-Sent Events
      parameters:
        - name: types
          in: query
          schema:
            type: array
            items:
              type: string
              enum: [threat, network, behavioral, osint]
        - name: priority
          in: query
          schema:
            type: string
            enum: [critical, high, medium, low]
      responses:
        '200':
          description: SSE stream established
          content:
            text/event-stream:
              schema:
                type: string
                format: event-stream

  /intelligence/analyze:
    post:
      tags:
        - Intelligence
      summary: Analyze intelligence data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntelligenceData'
      responses:
        '200':
          description: Analysis results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisResult'

  /threats/score:
    post:
      tags:
        - Threats
      summary: Calculate threat score
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                indicators:
                  type: array
                  items:
                    $ref: '#/components/schemas/ThreatIndicator'
      responses:
        '200':
          description: Threat score calculated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreatScore'

  /threats/{threatId}:
    get:
      tags:
        - Threats
      summary: Get threat details
      parameters:
        - name: threatId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Threat details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreatDetails'

  /war-room/sessions:
    get:
      tags:
        - War Room
      summary: List active war room sessions
      responses:
        '200':
          description: Active sessions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WarRoomSession'

  /war-room/sessions:
    post:
      tags:
        - War Room
      summary: Create new war room session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWarRoomRequest'
      responses:
        '201':
          description: Session created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarRoomSession'

  /war-room/sessions/{sessionId}/join:
    post:
      tags:
        - War Room
      summary: Join war room session
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Joined session
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  wsUrl:
                    type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key

  schemas:
    IntelligenceData:
      type: object
      required:
        - type
        - payload
        - source
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum: [intelligence, threat, network, behavioral]
        payload:
          type: object
        source:
          type: string
        timestamp:
          type: string
          format: date-time
        priority:
          type: string
          enum: [critical, high, medium, low]

    AnalysisResult:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
          enum: [complete, processing, failed]
        results:
          type: object
          properties:
            threatLevel:
              type: string
            indicators:
              type: array
              items:
                $ref: '#/components/schemas/ThreatIndicator'
            recommendations:
              type: array
              items:
                type: string

    ThreatIndicator:
      type: object
      required:
        - type
        - value
      properties:
        id:
          type: string
        type:
          type: string
          enum: [ip, domain, hash, behavioral, network]
        value:
          type: string
        confidence:
          type: number
          minimum: 0
          maximum: 1
        source:
          type: string
        timestamp:
          type: string
          format: date-time
        metadata:
          type: object

    ThreatScore:
      type: object
      properties:
        overallScore:
          type: number
          minimum: 0
          maximum: 100
        riskLevel:
          type: string
          enum: [critical, high, medium, low, info]
        indicators:
          type: array
          items:
            $ref: '#/components/schemas/ThreatIndicator'
        analysis:
          type: object
          properties:
            category:
              type: string
            confidence:
              type: number
            impact:
              type: number
            likelihood:
              type: number
        recommendations:
          type: array
          items:
            type: string
        timestamp:
          type: string
          format: date-time

    ThreatDetails:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        score:
          $ref: '#/components/schemas/ThreatScore'
        timeline:
          type: array
          items:
            type: object
            properties:
              timestamp:
                type: string
                format: date-time
              event:
                type: string
              severity:
                type: string

    WarRoomSession:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [active, paused, completed]
        participants:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              role:
                type: string
              joinedAt:
                type: string
                format: date-time
        createdAt:
          type: string
          format: date-time
        threat:
          $ref: '#/components/schemas/ThreatDetails'

    CreateWarRoomRequest:
      type: object
      required:
        - name
        - threatId
      properties:
        name:
          type: string
        description:
          type: string
        threatId:
          type: string
        participants:
          type: array
          items:
            type: string